export const BUY_CAKE = "BUY_CAKE";
export const BUY_ICE_CREAM = "BUY_ICE_CREAM";
export const GET_USERS_INITIALLY = "GET_USERS_INITIALLY";
export const GET_USERS_SUCCESSFULLY = "GET_USERS_SUCCESSFULLY";
export const GET_USERS_UNSUCCESSFULLY = "GET_USERS_UNSUCCESSFULLY";
